AllCops:
  NewCops: disable
  Exclude:
    - bin/bundle
    - node_modules/**/*
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb

Style/Documentation:
  Enabled: false
