AllCops:
  NewCops: disable
  Exclude:
    - vendor/**/*
    - bin/bundle
    - node_modules/**/*
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
    - lib/tasks/auto_annotate_models.rake
    - db/schema.rb
    - db/migrate/20200622040011_create_active_storage_tables.active_storage.rb

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - app/controllers/podcasts_controller.rb
    - db/migrate/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - app/views/podcasts/show.rss.builder
